### ISSUE TITLE
ارور بعد از نصب

### ISSUE THREAD

**Issue by AliROCK66** [redpilllabs/Rainb0w#3]
سلام
بعد از نصب این ارور رو میده سرور اوبنتو 22.04 هست

Traceback (most recent call last):
  File "/root/Rainb0w/lib/configurator.py", line 20, in <module>
    from proxy.blocky import config_doh_dot
  File "/root/Rainb0w/lib/proxy/blocky.py", line 4, in <module>
    from utils.helper import load_yaml, save_yaml
  File "/root/Rainb0w/lib/utils/helper.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Python configurator did not finish successfully!

**Comment by kyochikuto** [comment]
آیا اخرین نسخه اسکریپت رو روی یک سرور خام کپی کردید؟

این ماژول رو می تونید با دستور `pip install -U requests` نصب کنید.
